const scorerData = [
    {
        id:1,
        player:"Mohsin",
        Goals:2,
        matchPlayed:1,
    },
    {
        id:2,
        player:"Naeem",
        Goals:1,
        matchPlayed:1,
    },
    {
        id:3,
        player:"Zulqarnain",
        Goals:1,
        matchPlayed:1,
    },
    {
        id:4,
        player:"Atique",
        Goals:1,
        matchPlayed:1,
    },
    {
        id:5,
        player:"Hassan",
        Goals:1,
        matchPlayed:1,
    },
    {
        id:6,
        player:"Amanullah",
        Goals:1,
        matchPlayed:1,
    },
    {
        id:7,
        player:"Bilal",
        Goals:0,
        matchPlayed:1,
    },
    {
        id:8,
        player:"Azam",
        Goals:0,
        matchPlayed:1,
    },
    {
        id:9,
        player:"Zuraiz",
        Goals:0,
        matchPlayed:1,
    },
    {
        id:10,
        player:"Khurram",
        Goals:0,
        matchPlayed:1,
    },
    {
        id:11,
        player:"Ali Raza",
        Goals:0,
        matchPlayed:1,
    },
    {
        id:12,
        player:"Asan Lali",
        Goals:0,
        matchPlayed:1,
    },
]
export default scorerData