const scorerData = [
    {
        id:1,
        player:"Mohsin",
        Goals:2,
        matchPlayed:1,
        Assist:0,
        bg:"aquamarine"
    },
    {
        id:2,
        player:"Naeem",
        Goals:1,
        matchPlayed:1,
        Assist:1,
        // bg:"#70e774",
        bg:"#f56d6d",
    },
    {
        id:3,
        player:"Zulqarnain",
        Goals:1,
        matchPlayed:1,
        Assist:0,
        bg:"#f6e562"
    },
    {
        id:4,
        player:"Atique",
        Goals:1,
        matchPlayed:1,
        Assist:1,
        bg:"#87e1ff"
    },
    {
        id:5,
        player:"Hassan",
        Goals:1,
        matchPlayed:1,
        Assist:0,
        bg:"#c7b9ee"
    },
    {
        id:6,
        player:"Zeeshan",
        Goals:0,
        matchPlayed:1,
        Assist:1,
        bg:"#f1b18c"
    },
    {
        id:7,
        player:"Bilal",
        Goals:0,
        matchPlayed:1,
        Assist:0,
        bg:"#f5abe5"
    },
    {
        id:8,
        player:"Azam",
        Goals:0,
        matchPlayed:1,
        Assist:0,
        bg:"#afc5ce"
    },
    {
        id:9,
        player:"Zuraiz",
        Goals:0,
        matchPlayed:1,
        Assist:1,
        bg:"#cbc6c8"
    },
    {
        id:10,
        player:"Khurram",
        Goals:0,
        matchPlayed:1,
        Assist:0,
        bg:"#61dd87"
    },
    {
        id:11,
        player:"Ali Raza",
        Goals:0,
        matchPlayed:1,
        Assist:0,
        bg:"#87d0f2"
    },
    {
        id:12,
        player:"Asad Lali",
        Goals:0,
        matchPlayed:1,
        Assist:0,
        bg:"#bb9df6"
    },
    {
        id:13,
        player:"Amanullah",
        Goals:1,
        matchPlayed:1,
        Assist:0,
        bg:"#fc4646"
    },
]
export default scorerData